log:
  level: debug
  format: console
  color: true
o11y:
  host: 0.0.0.0
  port: 9090
gin:
  mode: debug
http:
  host: 0.0.0.0
  port: 8080
  enable_cors: true
  enable_auth: false
  read_only_tokens: []
  read_write_tokens: []
  max_upload_size: 5242880
  read_timeout: 15s
  write_timeout: 300s
  shutdown_timeout: 15s
file:
  root: "."
  naming_strategy: uuid
