## Default configuration value for the application.
# Uncomment and modify the following lines to customize the configuration.

# log:
#   level: debug
#   format: console
#   color: true

# o11y:
#   host: 0.0.0.0
#   port: 9090

# gin:
#   mode: debug

# http:
#   host: 0.0.0.0
#   port: 8080
#   enable_cors: false
#   enable_auth: false
#   read_only_tokens: []
#   read_write_tokens: []
#   max_upload_size: 5242880
#   read_timeout: 15s
#   write_timeout: 300s
#   idle_timeout: 60s
#   shutdown_timeout: 15s

# file:
#   root: "./data/files"
#   database: "./data/sqlite.db"
#   web_root: "./web/dist"
#   web_upload_path: "./files"
